# Generated by Django 6.0 on 2025-12-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemMQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
