# Generated by Django 6.0 on 2025-12-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensagemMQTT',
        ),
    ]
